; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Documents and Settings\071115.HIDOMAIN\My Documents\Visual Studio 2010\Projects\DynamicDllImport\asmproject\asmproject.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG29862 DB	'nothing to do.', 00H
CONST	ENDS
PUBLIC	_add
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\documents and settings\071115.hidomain\my documents\visual studio 2010\projects\dynamicdllimport\asmproject\asmproject.cpp
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu
rtc$IMZ	ENDS
_TEXT	SEGMENT
_c$ = -4						; size = 4
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_add	PROC
; Line 8
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
; Line 12
	mov	eax, DWORD PTR _a$[ebp]
; Line 13
	add	eax, DWORD PTR _b$[ebp]
; Line 14
	mov	DWORD PTR _c$[ebp], eax
; Line 16
	mov	eax, DWORD PTR _c$[ebp]
; Line 17
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_add	ENDP
_TEXT	ENDS
PUBLIC	_hello
; Function compile flags: /Odtp /RTCsu
_TEXT	SEGMENT
_s$ = 8							; size = 4
_hello	PROC
; Line 20
	push	ebp
	mov	ebp, esp
; Line 21
	mov	eax, DWORD PTR _s$[ebp]
; Line 22
	pop	ebp
	ret	0
_hello	ENDP
_TEXT	ENDS
PUBLIC	_nothing
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp /RTCsu
_TEXT	SEGMENT
_nothing PROC
; Line 25
	push	ebp
	mov	ebp, esp
	push	esi
; Line 26
	mov	esi, esp
	push	OFFSET $SG29862
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 27
	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
_nothing ENDP
_TEXT	ENDS
END
